### ISSUE TITLE
Fatal MySQL error when using eztagcloud operator

### ISSUE THREAD

**Issue by dfritschy** [ezsystems/eztags#102]
I have encountered the following fatal MYSQL error when using `eztagcloud`
```
PHP Fatal error:  mysqli_query(): Query error (1064): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')  AND  eztags.id = eztags_keyword.keyword_id  AND \n eztags.language_mask & 7 > ' at line 2. Query: SELECT DISTINCT eztags.*, eztags_keyword.keyword AS keyword, eztags_keyword.locale AS locale\n                    FROM   eztags, eztags_keyword WHERE  id IN (  )  AND  eztags.id = eztags_keyword.keyword_id  AND \n eztags.language_mask & 7 > 0 \n  AND \n ( eztags_keyword.language_id & eztags.language_mask > 0 AND\n     ( (   eztags.language_mask - ( eztags.language_mask & eztags_keyword.language_id ) ) & 1 )\n   + ( ( ( eztags.language_mask - ( eztags.language_mask & eztags_keyword.language_id ) ) & 2 ) )\n   + ( ( ( eztags.language_mask - ( eztags.language_mask & eztags_keyword.language_id ) ) & 4 ) )\n   <\n     ( eztags_keyword.language_id & 1 )\n   + ( ( eztags_keyword.language_id & 2 ) )\n   + ( ( eztags_keyword.language_id & 4 ) )\n ) \n  ORDER BY ezt
```
The error is thrown in the fetch on line https://github.com/ezsystems/eztags/blob/master/autoloads/eztagscloud.php#L189

Without doing too much research I think it is the result of the following setup:
* Content tree with different subtrees for different siteaccesses
* Tagged Content in siteaccess A (main location) being also published in siteaccess B (additional location for same content)
* Tagcloud fetched in siteaccess B with limitation to subtree B

The problem does not arise when the tagcloud is fetched staring with root node 2.

I am not yet sure what the behaviour of tags should be when using multiple locations for the tagged content, but I have made a quick fix to eliminate the fatal error.

**Comment by emodric** [comment]
Looks good, thanks!
