### ISSUE TITLE
Auto suggest dropdown doesn't close when changing focus

### ISSUE THREAD

**Issue by thiagocamposviana** [ezsystems/eztags#108]
It is desired that the auto suggestion dropdown closes whenever the user clicks somewhere else in the page or change the focus to another field.

Right now it is necessary to press "Esc" in order to close the dropdown.

**Comment by emodric** [comment]
Hi! Thanks for the issue report! I'll take a look at it in coming days, together with the other issue.

**Comment by emodric** [comment]
Fixed in d4139f7773685fe8981672f33f48f77efcb046ea

Thanks for the report @thiagocamposviana !
