### ISSUE TITLE
error in the logs: explode() expects parameter 2 to be string, array given in /var/www/site/ezpublish_legacy/extension/eztags/classes/ezjsctags.php on line 66 

### ISSUE THREAD

**Issue by gggeek** [ezsystems/eztags#114]
Using ezp 5.4.10 with eztags-ls 2.2.1: the 'tag_ids' pos var is an array, not a sting

**Comment by gggeek** [comment]
Besides leaving error messages in the logs, this also has the effect that the tags suggested when the editor adds one tag to a content are not really pertinent (related to the first tag / existing tags)

**Comment by emodric** [comment]
Fixed by #115
