### ISSUE TITLE
Add events on editing tags, so that ez5 slots can be hooked up and expire varnish cache

### ISSUE THREAD

**Issue by gggeek** [ezsystems/eztags#116]
Using the ez4 events mechanism, we should be able to replicate the same behaviour as we have with the Content Repo, namely:

when a user renames/deletes a tag, expire the varnish cache for all contents that display that tag (using the x-tag-id http header)

**Comment by emodric** [comment]
Hey @gggeek!

Thanks for your issue. There are already some `ezpEvent` events being dispatched on tag edit: https://github.com/ezsystems/eztags/blob/master/modules/tags/edit.php#L158

Is this what you're looking for, or is it something different?

**Comment by gggeek** [comment]
Doh, I must have been blind! :-O

I will look into the Bundle part of this then
