### ISSUE TITLE
solr index not updated when deleting tags and delayedindexing is disabled

### ISSUE THREAD

**Issue by gggeek** [ezsystems/eztags#118]
The problem comes from `eZTagsObject::recursivelyDeleteTag`, which first calls `$this->registerSearchObjects` and only then `$this->remove`.
So when the reindexation happens, the tag is still in the db, and the object gets reindexed with the tag, instead of being reindexed without it

**Comment by gggeek** [comment]
Note that the same might be happening as well in other situations, where the registerSearchObjects call is made before further database operations, such as in view `merge.php`

**Comment by gggeek** [comment]
PR: https://github.com/ezsystems/eztags/pull/120

**Comment by emodric** [comment]
Closed by #120
