### ISSUE TITLE
Documentation update: sort_by parameter not boolean

### ISSUE THREAD

**Issue by benkmugo** [ezsystems/eztags#122]
Hi @emodric 
I was just working on something with eZ Tags and noticed that the sort direction parameters in the documentation don't seem to be right (anymore?).
https://github.com/ezsystems/eztags/blob/master/doc/USAGE.md#tagslist-tagstree

Using true()/false() has no effect, where as asc/desc works fine.

Going through the extension code seems to confirm that:
https://github.com/ezsystems/eztags/blob/master/classes/eztagsobject.php#L1193

Happy to provide a PR with documentation updates if needed.

Thanks,
Ben

**Comment by emodric** [comment]
Hi @benkmugo 

Ofcourse, yes, thank you! It will be appreciated!

BTW, it's good to hear somone still finds this useful :)
